services:

  pg-tms:
    image: postgres:latest
    container_name: tms-db
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /var/docker/postgres/${TMS_NAME}:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${TMS_PG_DB}
      - POSTGRES_PASSWORD=${TMS_PG_PASSWORD}
      - POSTGRES_USER=${TMS_PG_USER}
    ports:
      - ${TMS_PG_PORT}:5432

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  tms:
    build: .
    image: ${TMS_NAME}
    container_name: ${TMS_NAME}
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      pg-tms:
        condition: service_started
      kafka:
        condition: service_started
    ports:
      - ${TMS_PORT}:${TMS_PORT}
    environment:
      - TMS_PG_URL=jdbc:postgresql://tms-db:5432/${TMS_PG_DB}
      - TMS_PG_USER=${TMS_PG_USER}
      - TMS_PG_PASSWORD=${TMS_PG_PASSWORD}
      - TMS_NAME=${TMS_NAME}
      - TMS_PORT=${TMS_PORT}
      - TMS_KAFKA_SERVER=kafka:9092
      - TMS_EMAIL_USER=${TMS_EMAIL_USER}
      - TMS_EMAIL_PASSWORD=${TMS_EMAIL_PASSWORD}
