spring:
  application:
    name: task-manager-aop
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${TMS_PG_URL}
    username: ${TMS_PG_USER}
    password: ${TMS_PG_PASSWORD}
  liquibase:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
  sql:
    init:
      mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: ${TMS_KAFKA_SERVER}
  mail:
    username: ${TMS_EMAIL_USER}
    password: ${TMS_EMAIL_PASSWORD}
    host: smtp.yandex.ru
    port: 587
server:
  port: ${TMS_PORT}

app:
  kafka:
    consumer:
      group-id: task-manager
      sessionTimeout: 15000
      maxPartitionFetchBytes: 300000
      maxPollRecords: 1
      maxPollIntervalsMs: 3000
    topics:
      updateTask: update-task-status




